### PR TITLE
Support `λ` as well as `lambda`.

### PR DESCRIPTION
**Pull request by mjgpy3**
Not super important but seems like something that's pretty well
supported (racket & guile but not chicken).

### CODE REVIEW

**Comment by mjgpy3** [comment]
Hmm, works on my machine!!!

**Review by Kazark — APPROVED** [review]
Love it. Let's get the builds figured out so we can merge.

**Comment by Kazark** [comment]
Oh wow that looks like a fun build error... O.O C'mon guys, it's 2019... can't a guy just use UTF-8 in his source code yet!?!

I wonder if Travis is running and old version of Guile.

**Comment by mjgpy3** [comment]
@Kazark I think it's because they're not running in a real terminal. I had basically the same issue in another project last month!

**Pull request merged**
