### PR TITLE
Synthesize `if`.

### PR DESCRIPTION
**Pull request by mjgpy3**
Here are some cases I ran through

```lisp
2-t> (if 1 2 1)
2 : 1
2-t> (if (lambda (x) x) 2 1)
(if (lambda (x) x) 2 1) : #<unspecified>
2-t> (if 42 (lambda (x) 4) (lambda (y) 4))
#<procedure (? x)> : 2
```

Also, for what it's worth
```lisp
2-t> (if 1 2 3 4)
(if 1 2 3 4) : #<unspecified>
2-t> (if 1 2)
(if 1 2) : #<unspecified>
```

### CODE REVIEW

**Review by Kazark — COMMENTED** [review]
You have showed me up in your Listfu with all your crazy `cadddr`s and whatnot! :smile:

**Comment by Kazark** [comment]
I really like your results, but I'm unsure about the approach. Isn't `if` a macro, for which `cond` is the more fundamental form? I guess if you were treating `if` as a special form (since it's not a function), you would have to add special rules for it. But I haven't worked through how macros should work. Do we do our own expansions, and only pass expanded code to Scheme? But if not, do we not support macros? Or do we extend the type system for every one? (No, definitely not that.)

Scheme's macro system, though hygienic, is not total, in that you have no guarantee that macro expansion will ever complete. In a language focused on totality, that seems bad (even though that would be at compile time, not run time, due to phase separation). I do have an idea for what it would take to build terminating-by-construction macro system that ought to be significantly powerful; however, I'm still a total n00b at Lisp macros; I've never even written one! I'm in the middle of reading a paper on hygienic macros, which are become the standard kind of macros, but I think the Racket folks may have pushed the bubble even further in terms of macro safety, and I haven't read any of their stuff on it yet.

Thanks for jumping in and making contributions! Let me know what you're thoughts are after these comments. I'm not necessarily opposed to merging this, but it won't scale as a strategy. If we need `if` for now as a way of being able to write a certain amount of code, that's cool---but we'll probably want to change it later.

Let me know what you think.

**Comment by Kazark** [comment]
Another thing is, because of the way `#<unspecified>` works in Chicken, I would argue that `(if 1 2)` should be well-typed because IMO `#<unspecified> : 1`; unless we did not want to leak those kinds of details from Chicken (I don't know if this is standard in Scheme, and how much we want to stay Scheme-flavor-agnostic).

**Comment by mjgpy3** [comment]
@Kazark I can't remember if the standard is to have `if` or `cond` as the special form, though my suspicion is that either would work. On second though, I bet it's not standard and varies by implementation. I personally prefer `cond` in terms of `if` because `if` is simpler and implies a simpler core but that's really just, like, well, uh, my opinion dude :sunglasses: 

I'll have to ponder the macro question some more. It's well beyond my "lispfu" and philosophical capabilities at the moment.

I can buy `#<unspecified> : 1`. I got confused by it for a moment because I though you were saying that things that have `#<unspecified>` types have types of `1`! Like I said before, I can't count to level 2!

Therefore, I'll make `(if cnd csq) : 1`  be true. It feels right to bleed as much LISP concepts up as possible (when in Rome) and it seems that guile also has some notion of `unspecified`.

**Comment by Kazark** [comment]
Good point about Guile, though `(cond)` is illegal there:

    GNU Guile 2.2.3
    Copyright (C) 1995-2017 Free Software Foundation, Inc.

    Guile comes with ABSOLUTELY NO WARRANTY; for details type `,show w'.
    This program is free software, and you are welcome to redistribute it
    under certain conditions; type `,show c' for details.

    Enter `,help' for help.
    scheme@(guile-user)> (begin (display (if #f 2)) (display "\n"))
    #<unspecified>
    scheme@(guile-user)> (cond)
    While compiling expression:
    Syntax error:
    unknown file:2:0: source expression failed to match any pattern in form (cond)
    scheme@(guile-user)>

**Comment by Kazark** [comment]
The reason I brought up `cond` is that if I remember correctly, that was one of McCarthy's original primitives. At one point I thought it was more powerful than `if`, but I can't remember why now... I was probably confusing myself. I'm happy to merge this---but maybe we should add some comments reflecting this discussion to the source code, for future reference?

**Review by Kazark — APPROVED** [review]

**Comment by mjgpy3** [comment]
@Kazark I think that you're right about `cond` being an original primitive though I also don't remember why it's the _right_ one.

**Pull request merged**
